version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3030 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3030:3030"
    depends_on:
      - db